### ISSUE TITLE
Crash in `expect-expect` rule when calling function without assignment

### ISSUE THREAD

**Issue by EvHaus** [veritem/eslint-plugin-vitest#20]
The following code:

```typescript
import {describe, expect, it} from 'vitest';
import {withUser} from '../../../myMock';

describe('my test', () => {
	it('should do something', () => {
		withUser(null);
		expect(1).toEqual(1);
	});
});
```

causes `eslint-plugin-vitest` to crash with:

```
Oops! Something went wrong! :(

ESLint: 8.28.0

TypeError: Cannot read properties of undefined (reading 'callee')
Occurred while linting /home/myproject/pages/api/component/DELETE.test.ts:6
Rule: "vitest/expect-expect"
    at /home/myproject/node_modules/.pnpm/eslint-plugin-vitest@0.0.20_hsf322ms6xhhd4b5ne6lb74y4a/node_modules/eslint-plugin-vitest/dist/index.cjs:309:62
    at Array.some (<anonymous>)
    at CallExpression[callee.name=/^(it|test)$/] (/home/myproject/node_modules/.pnpm/eslint-plugin-vitest@0.0.20_hsf322ms6xhhd4b5ne6lb74y4a/node_modules/eslint-plugin-vitest/dist/index.cjs:307:32)
    at ruleErrorHandler (/home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/linter.js:1115:28)
    at /home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/myproject/node_modules/.pnpm/eslint@8.28.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

I think it's because of the `withUser` function which doesn't have any assignment.

**Comment by Maxim-Mazurok** [comment]
Same error:
```ts
describe("tickForFormula", () => {
  it("works for currency", () =>
    expect(
      tickForFormula(new Tick(new Currency("uah"), new Currency("aud")))
    ).toBe("CURRENCY:UAHAUD"));
});
```

```
> eslint --fix --max-warnings 0 .


Oops! Something went wrong! :(

ESLint: 8.29.0

TypeError: Cannot read properties of undefined (reading 'length')
Occurred while linting C:\Users\maxim.mazurok\transactions\legacy\analytics\util.spec.ts:2
Rule: "vitest/expect-expect"
    at C:\Users\maxim.mazurok\transactions\node_modules\eslint-plugin-vitest\dist\index.cjs:308:30
    at Array.some (<anonymous>)
    at CallExpression[callee.name=/^(it|test)$/] (C:\Users\maxim.mazurok\transactions\node_modules\eslint-plugin-vitest\dist\index.cjs:307:32)
    at ruleErrorHandler (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\linter.js:1115:28)
    at C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:297:26)    at NodeEventGenerator.applySelectors (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:340:14)    
```

**Comment by Maxim-Mazurok** [comment]
Changing `if (arg?.body?.body.length) {` to `if (arg?.body?.body?.length) {` seems to fix the issue, will use that with `npx patch-package` for now

**Comment by Maxim-Mazurok** [comment]
Also similar problem wit this test:
```ts
it("logs message when DEBUG=true", () => {
    // arrange
    process.env.DEBUG = "true";
    console.log = jest.fn();
    const message = "some message";

    // act
    debug(message);

    // assert
    expect(console.log).toHaveBeenCalledWith(message);
  });
```

```
Oops! Something went wrong! :(

ESLint: 8.29.0

TypeError: Cannot read properties of undefined (reading 'object')
Occurred while linting C:\Users\maxim.mazurok\transactions\legacy\balances\common\helpers.test.ts:52
Rule: "vitest/expect-expect"
    at C:\Users\maxim.mazurok\transactions\node_modules\eslint-plugin-vitest\dist\index.cjs:310:55
    at Array.some (<anonymous>)
    at CallExpression[callee.name=/^(it|test)$/] (C:\Users\maxim.mazurok\transactions\node_modules\eslint-plugin-vitest\dist\index.cjs:308:32)
    at ruleErrorHandler (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\linter.js:1115:28)
    at C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:297:26)    at NodeEventGenerator.applySelectors (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\Users\maxim.mazurok\transactions\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
```

And a similar "fix" - replace `return arg.body.body[0].expression?.callee.object.callee.name === "expect";` with `return arg.body.body[0].expression?.callee?.object.callee.name === "expect";`

**Comment by Maxim-Mazurok** [comment]
@veritem this still doesn't seem to work, maybe a regression. Here's a minimal reproduction:

```ts
import { expect, it } from "vitest";

const myFunc = () => {};

it("works", () => expect(myFunc()).toBe(undefined));
```

Here's the error:
```
Oops! Something went wrong! :(

ESLint: 8.31.0

TypeError: Cannot read properties of undefined (reading 'length')
Occurred while linting my_project\legacy\analytics\util.spec.ts:5
Rule: "vitest/expect-expect"
    at my_project\node_modules\eslint-plugin-vitest\dist\index.cjs:323:30
    at Array.some (<anonymous>)
    at CallExpression[callee.name=/^(it|test)$/] (my_project\node_modules\eslint-plugin-vitest\dist\index.cjs:322:32)
    at ruleErrorHandler (my_project\node_modules\eslint\lib\linter\linter.js:1115:28)
    at my_project\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (my_project\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (my_project\node_modules\eslint\lib\linter\node-event-generator.js:297:26)  
    at NodeEventGenerator.applySelectors (my_project\node_modules\eslint\lib\linter\node-event-generator.js:326:22) 
    at NodeEventGenerator.enterNode (my_project\node_modules\eslint\lib\linter\node-event-generator.js:340:14) 
```

```
npx envinfo

  System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 39.38 GB / 63.68 GB
  Binaries:
    Node: 19.3.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 9.2.0 - ~\AppData\Local\nvs\default\npm.CMD
```

```
"@typescript-eslint/eslint-plugin": "5.48.1",
"eslint": "8.31.0",
"eslint-import-resolver-typescript": "3.5.3",
"eslint-plugin-import": "2.27.4",
"eslint-plugin-jest": "27.2.1",
"eslint-plugin-unicorn": "45.0.2",
"eslint-plugin-vitest": "0.0.29",
```
