### ISSUE TITLE
[regression] Crash in expect-expect rule when calling function without assignment

### ISSUE THREAD

**Issue by Maxim-Mazurok** [veritem/eslint-plugin-vitest#40]
@veritem this still doesn't seem to work in the latest version, maybe a regression. Here's a minimal reproduction:

```ts
import { expect, it } from "vitest";

const myFunc = () => {};

it("works", () => expect(myFunc()).toBe(undefined));
```

Here's the error:
```
Oops! Something went wrong! :(

ESLint: 8.31.0

TypeError: Cannot read properties of undefined (reading 'length')
Occurred while linting my_project\legacy\analytics\util.spec.ts:5
Rule: "vitest/expect-expect"
    at my_project\node_modules\eslint-plugin-vitest\dist\index.cjs:323:30
    at Array.some (<anonymous>)
    at CallExpression[callee.name=/^(it|test)$/] (my_project\node_modules\eslint-plugin-vitest\dist\index.cjs:322:32)
    at ruleErrorHandler (my_project\node_modules\eslint\lib\linter\linter.js:1115:28)
    at my_project\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (my_project\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (my_project\node_modules\eslint\lib\linter\node-event-generator.js:297:26)  
    at NodeEventGenerator.applySelectors (my_project\node_modules\eslint\lib\linter\node-event-generator.js:326:22) 
    at NodeEventGenerator.enterNode (my_project\node_modules\eslint\lib\linter\node-event-generator.js:340:14) 
```

```
npx envinfo

  System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 39.38 GB / 63.68 GB
  Binaries:
    Node: 19.3.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 9.2.0 - ~\AppData\Local\nvs\default\npm.CMD
```

```
"@typescript-eslint/eslint-plugin": "5.48.1",
"eslint": "8.31.0",
"eslint-import-resolver-typescript": "3.5.3",
"eslint-plugin-import": "2.27.4",
"eslint-plugin-jest": "27.2.1",
"eslint-plugin-unicorn": "45.0.2",
"eslint-plugin-vitest": "0.0.29",
```

_Originally posted by @Maxim-Mazurok in https://github.com/veritem/eslint-plugin-vitest/issues/20#issuecomment-1383050218_

**Comment by veritem** [comment]
Are you still experiencing the same issue on the latest version? I sent a fix, so if that's the case, feel free to reopen this.

**Comment by Maxim-Mazurok** [comment]
I'm on `v0.0.32` and can confirm it no longer throws, thank you!
